### ISSUE TITLE
Engineer backpack size

### ISSUE THREAD

**Issue by Helldog217** [143rd-Siege-Army/143rdMod#101]
The engineers on top of having to carry heavy weapons primarily and anti tank equipment also need more standard kit than regular infantry. Mine detectors, Tool kits, Explosives, Mines and various other pieces of equipment that are quite bulky and standard issue. 

The regular engineer backpack can only carry the same amount as a standard infantryman's backpack. If possible could it be increased to allow us to carry more of our necessary supplies and equipment? At the very least could it be increased by 8 lbs, the same weight as the Toolkit that's mandatory to carry and weighs the same as a melta gun

**Comment by 143Rowan** [comment]
This work has already been done, waiting on a new release of the mod.
