### ISSUE TITLE
Smoke/Chaff Launchers for Leman Russes

### ISSUE THREAD

**Issue by Venture143** [143rd-Siege-Army/143rdMod#104]
add smoke/chaff launchers for Leman Russes, as a countermeasure to air's AGM's that can lock on and one hit Lemans. Limit smoke/Chaff to 1 or 2 launches maximum so that they will need to be conserved over the duration of a operation

**Comment by Siggyfreed** [comment]
Same request as issue #98 , will close this one as the feature is on a to-do list for the other issue.
