### ISSUE TITLE
Possibility for primary bolt/plasma pistol

### ISSUE THREAD

**Issue by BrotherGreen** [143rd-Siege-Army/143rdMod#106]
Nothing necessary, just wanted to know what the possibilities for getting mainhand pistols mainly so that cumtzars can bring a melee weapons as well for style points

**Comment by Siggyfreed** [comment]
This is a possibility but implementation will likely involve the breaking of animations. I will look into it to see how rough it is and if it is a possibility.

**Comment by Siggyfreed** [comment]
implemented and will be in the v2.0 content push. animations are absolutely fucked but the gun fires properly and that's the important thing
