### ISSUE TITLE
Update to Stubber ammo

### ISSUE THREAD

**Issue by SMGHunter16** [143rd-Siege-Army/143rdMod#108]
add a tracer to each of the special ammo types. probably 1 in every ten. could look at and salvage code from one of the vanilla mixed ammo boxes, and would give us a more immersive feel

**Comment by Siggyfreed** [comment]
adding on to tasking for that last 10 bullet thingie

**Comment by Siggyfreed** [comment]
implementation complete, will be in the v2.0 release
