### ISSUE TITLE
TIOW Smoke Grenades

### ISSUE THREAD

**Issue by Siggyfreed** [143rd-Siege-Army/143rdMod#13]
currently bounce at approx. 100km/h. Should look into it to see if that velocity can be adjusted.

**Comment by qwertythreeight** [comment]
Can we possibly make the GL smokes explode into a smoke cloud when it first hits an object, ala smoke missiles for the Krieg AT launcher?

**Comment by Siggyfreed** [comment]
Closing ticket due to this issue being an arma physics engine bug, outside of the scope of this mod.
