### ISSUE TITLE
Cadian configs missing APC entries

### ISSUE THREAD

**Issue by Venture143** [143rd-Siege-Army/143rdMod#14]
causing issues with error calls when loading into Zeus in a ALIVE mission. enclosed configs should remedy the error

**Comment by Venture143** [comment]
[New Cadian Fix.zip](https://github.com/143rd-Siege-Army/143rdMod/files/4497881/New.Cadian.Fix.zip)

**Comment by Venture143** [comment]
[New Cadian Fix.zip](https://github.com/143rd-Siege-Army/143rdMod/files/4499407/New.Cadian.Fix.zip)
with updated readme file

**Comment by Siggyfreed** [comment]
adding with 1.2 release
