### ISSUE TITLE
Grenade Launcher Krak rounds cause spalling/fragmentation

### ISSUE THREAD

**Issue by qwertythreeight** [143rd-Siege-Army/143rdMod#17]
Krak grenades fired from the Cadian grenade launcher cause fragmentation, but thrown krak grenades work properly and leave no fragmentation. Also some testing has shown two to three magazines of Krak GL rounds can blow up a Russ. May need further testing as Varv has said it was due to a shot hitting the ammo rack.

**Comment by Siggyfreed** [comment]
Taking update: Cadian krak grenades should not cause spalling/fragmentation.
