### ISSUE TITLE
Tau Infantry + Hammerhead Weaponry too weak

### ISSUE THREAD

**Issue by Venture143** [143rd-Siege-Army/143rdMod#21]
Common Critique from my Fun Op was tau Infantrys inability to deal with Leman's at any range. might be worth looking into as part of the balance pass

**Comment by SchwererKonigstiger** [comment]
This is in addition to all Tau vehicle-mounted weapons (Hammerheads) being unable to scratch the Lemans as well.
I noted that only the missile drone can damage them - but it just scratches them really

**Comment by Siggyfreed** [comment]
affirm, we could either look at increasing tau ion rifle/hh damage values or lowering the leman armor to vanilla.

**Comment by jybelcher93** [comment]
@Siggyfreed Has this been addressed yet?

**Comment by Siggyfreed** [comment]
closing issue, weapon and vehicle balancing will now be handled through vanguard mod. further testing may be needed to find any other imbalances
