### ISSUE TITLE
Melee

### ISSUE THREAD

**Issue by Tactical-Loli** [143rd-Siege-Army/143rdMod#33]
perhaps increase the range and damage of melee weapons so as to actually see them used?

**Comment by Siggyfreed** [comment]
Melee weapon implementation is a little wonky, damage values are currently 3x vanilla. Test the weapons out in arsenal and lmk what adjustments you think need to be made.

**Comment by Tactical-Loli** [comment]
After doing some testing, it would seem that the "shots" are going
backwards. I have to literally turn my back on a unit if I want to actually
hit it

**Comment by jybelcher93** [comment]
Max Melee has been removed, I'm closing the issue.
