### ISSUE TITLE
2nd Platoon Engineer Vics with Supply Manifest

### ISSUE THREAD

**Issue by Lewddozer** [143rd-Siege-Army/143rdMod#34]
https://docs.google.com/spreadsheets/d/1hyAPnnMq7UF4hihTuf_7yFYn5HXxngop-pZBxcje2ao/edit?usp=sharing

The above link contains the class names and quantities we would like to have when we conduct operations. If possible could they please be loaded in a Centaur.

**Comment by Lewddozer** [comment]
Added Plasma Coolants in two sizes, added Saline in three sizes.

**Comment by Siggyfreed** [comment]
closing issue due to me never actually doing it and vehicle manifests no longer being required thanks to factory mod.
