### ISSUE TITLE
Type 14 ammo

### ISSUE THREAD

**Issue by roushjosh** [143rd-Siege-Army/143rdMod#36]
Can you make it where the Type 14's ammo is either lighter so 3 or 4 can be fit in the type 14 backpack or to make the Type 14's backback allow for more ammo to fit.

**Comment by Siggyfreed** [comment]
The T14 magazines were already adjusted to be half their base weight. Two full magazines are able to fit in the dedicated T14 backpack. This totals 600 rounds of ammunition or the equivalent of 60 standard Lucius Las packs. We won't be adjusting the weight any further to prevent making the T14 an overpowered weapon choice.
