### ISSUE TITLE
Type 14

### ISSUE THREAD

**Issue by Tactical-Loli** [143rd-Siege-Army/143rdMod#37]
it has come to multible people's attention that the Type 14 hotshot lasgun has less damage than it should. using server settings for more accuracy, i tested it alongside the lucius pattern lasgun, and found out that indeed it is true. the lucius has killed the targets using less shots than the type 14. as you most likely know, hotshot lasguns are meant to be harder hitting than the average lasgun, including the lucius pattern. just thought i would bring this up to ya

**Comment by Siggyfreed** [comment]
Current damage values for both weapons do not support this theory. The Hit value for the Lucius bolt is 10, while the value for the T14 is 11.6. The T14 also has a large magazine and higher RoF. Any adjustments to the weapon will potentially imbalance Krieg load outs. What method of testing are you using?

**Comment by deathknive** [comment]
I have noticed that both the T14 and the Hellgun both seem to under preform for their intended usage. I was planning on looking at that after I finish this stupid backpack.

**Comment by Tactical-Loli** [comment]
The testing I did was putting down 2 of various enemy types and testing
both weapons. The lucius killed faster (tested with single fire for type 14)

**Comment by Siggyfreed** [comment]
I'll take a look and attempt to repro
