### ISSUE TITLE
DK_143 Calling for LAMBS_Danger

### ISSUE THREAD

**Issue by GraniteRoyalWolf** [143rd-Siege-Army/143rdMod#38]
I've been getting a error Warning Message: Addon 'I_CDF' requires addon 'lambs_danger'

**Comment by Siggyfreed** [comment]
This is an issue with your local modlist. I would recommend verifying your mod files and, if the problem persists, redownload the LAMBS mods.

**Comment by 143Rowan** [comment]
Not an issue
