### ISSUE TITLE
Type 14 is a lot weaker than it used to be

### ISSUE THREAD

**Issue by RoyalUnai** [143rd-Siege-Army/143rdMod#39]
Not sure if compact reduced damage but on the op of 7/30/2020 it took 20 type 14 shots to kill one cadian trooper where a basic lasgun can kill them in 1-2 shots. Not sure why its debuffed like this (when it is) when the whole point of a hotshot lasgun is that its supposed to be stronger and over all better than basic lasguns

**Comment by jybelcher93** [comment]
I'd like to update this to set damage as the same as a krieg las rifle with increased penetration.
