### ISSUE TITLE
143rd Medicae Helmet

### ISSUE THREAD

**Issue by JakeHarleyKrieg** [143rd-Siege-Army/143rdMod#41]
Can we please get our white helmets back.

**Comment by jybelcher93** [comment]
Converted to a work item here: https://github.com/143rd-Siege-Army/143rdMod/issues/43

**Comment by Siggyfreed** [comment]
First implementation: helmet in game and in arsenal. Model file will need to be updated as Medicae Caduceus not present

**Comment by Siggyfreed** [comment]
Medicae helmets have been brought back, closing this issue.
