### ISSUE TITLE
Type 14

### ISSUE THREAD

**Issue by Tactical-Loli** [143rd-Siege-Army/143rdMod#48]
as of 8/13/2020, i tested the type 14, being informed that the fix went through, and found that it still does too little damage. while waiting for the op to start, i asked the zeus to spawn 6 OPFOR (all of which were exactly the same) and tested the lucius and type 14 on 3 each on the torso. the lucius downed one at 3 shots. the type 14 downed them at 7-8 shots. the type 14 still needs a damage rework after conclusion of said test

**Comment by Venture143** [comment]
looking at the compats code and what TIOW has, the only thing I could see as causing an issue is the caliber - in TIOW the caliber is 3 for the Lucius, maybe moving to that caliber for the Type 14 would help?

As is, the type 14 already does more damage in the compats settings (11.6 for the Type 14 vs 10 for the Lucius), so this might be the culprit. I can confirm in my own testing that the type 14 hits less hard then the Lucius except at literally point blank (pressing weapon against target) range

**Comment by 143Rowan** [comment]
@Venture143: It has a caliber of 3?? That's insane.
Let's bump the T14 up to 3 and see how that works then.

**Comment by Venture143** [comment]
@143Rowan TIOW goes big or goes home it seems

**Comment by Venture143** [comment]
Created Pull request to have Type 14 damage buffed to 12
