### ISSUE TITLE
Balance Cadian Gear for Loli's Op

### ISSUE THREAD

**Issue by deathknive** [143rd-Siege-Army/143rdMod#62]
the GD and TIOW armor and weapons need to be added to the compact to balance out against the kreiger gear. Dropping dead when the AI just drop unconscious is extremely fucking annoying.

**Comment by Siggyfreed** [comment]
GD and TIOW base armor and weapon profiles are already included within the compat. Atm players can currently tank 2x - 3x the amount of damage that AI can, and the Grenadier armor is tuned even higher than that.

**Comment by deathknive** [comment]
Well that is not happening in Op. Every member of grenadiers is having a problem with dropping dead after getting hit once with current opfor weapons. M36 kantrals. The only time I didn’t die immediately was when one shot broke both of my legs and gave me 9 major avulsions after penetrating a sandbag bunker.

**Comment by Siggyfreed** [comment]
I'll do some testing on current armor and damage values for Grenadier gear, as well as verifying mod files are correct on the server.

**Comment by Siggyfreed** [comment]
testing results indicated vanilla CSAT gear was adding to base vest armor values, led to imbalance. faction adjusted and CSAT gear retained for SLs
