### ISSUE TITLE
Steel Legion AT launcher needs a buff

### ISSUE THREAD

**Issue by SgtRocko** [143rd-Siege-Army/143rdMod#63]
With the introduction of the Steel Legion mod to the modlist, I and some of the other bois of the 919th have done some testing with the AT launcher that comes with the mod and quite like it's the passive lock-on feature. However, the damage of the launcher leaves a little more to be desired, struggling with heavier vehicles like Chimeras and Leman Russes. If the damage output could be improved to what the regular 143rd launcher can do, it would be much appreciated.

**Comment by Siggyfreed** [comment]
Currently any weapons or armor not within the TIOW mod aren't being looked at for balance passes, as other mods tend to balance their assets to vanilla levels. I do, however, plan on running a balance pass on TIOW vics to bring them more in line with vanilla levels, which should serve the same purpose as far as the SL AT launcher
