### ISSUE TITLE
Fix Melee

### ISSUE THREAD

**Issue by SchwererKonigstiger** [143rd-Siege-Army/143rdMod#7]
Melee weapons still need more range, and need to do far more damage.

**Comment by Siggyfreed** [comment]
after local testing damage doesn't seem low to me, the weapons have a rate of fire that can chew through armor. i can bump the range up some, however.

**Comment by Siggyfreed** [comment]
adding indirect damage on bullet location to make aim easier

**Comment by Siggyfreed** [comment]
on further testing: indirect damage wouldn't properly fix the issue. Will increase the range of melee weapons for next release. Damage values won't be adjusted.
