### ISSUE TITLE
Reduce Denilander armor?

### ISSUE THREAD

**Issue by RoyalUnai** [143rd-Siege-Army/143rdMod#71]
In the 919th op on the 25th of October 2020 I shot several Deniland milita in the chest, head, and every other body part with a TIOW Chimera's autocannon with HE loaded and it took 7~ HE rounds to actually kill or knock them out. Seems a little too stronk that they can take autocannon fire and laugh it off.

**Comment by Siggyfreed** [comment]
VR testing is showing the Denil boys are dying as they should, I'll drop a few in during the next few operations to make sure they're working overall.
