### ISSUE TITLE
Increased Krieger AT Backpack Capacity

### ISSUE THREAD

**Issue by NagaSadow1938** [143rd-Siege-Army/143rdMod#72]
Several people in 1-1 including myself believe the AT backpack needs to be able to carry at least 3 Krak Missiles on top of 7-10 Lasgun packs. At current, it is only capable of carrying 1 missile and a sufficient amount of Lasgun packs which makes AT carriers ineffective on their lonesome against armor which is most often the case as squads are often split up.

**Comment by Siggyfreed** [comment]
Carrying capacity on AT backpack has been doubled, give it a test run and report back here if it's still too light.

**Comment by NagaSadow1938** [comment]
I've tested the backpack on the training server and it is still too light.
I'd advise increasing the load to match the Type 14 powerpack or increase
the load 10lbs further than that. Matching would allow us to carry 3 Krak
Missiles and 6 Lasgun Packs.

**Comment by 143Rowan** [comment]
@NagaSadow1938: Can you give an estimated loadout you'd like the pack to carry?  I may or may not conform to that, but I'd like a baseline to compare against.  My first thoughts are to match it to one of the vanilla packs, so you could also just give that recommendation.

**Comment by Siggyfreed** [comment]
all krieg backpack carry weights have been increased per code rowan wrote. container sizes all match vanilla caryall capacity.
