### ISSUE TITLE
Increase Steel Legion Chest Rigs Armour Value

### ISSUE THREAD

**Issue by Pappeska** [143rd-Siege-Army/143rdMod#74]
Currently one shot from a TIOW or Grimdark lasgun is normally enough to insta-kill a player wearing any of the Steel Legion chest rigs if they're unlucky enough, we'd prefer to be able to still use the rigs as they have unique models which fit with the uniform.

**Comment by Siggyfreed** [comment]
SL vests are indeed weak as hell, but I'm having trouble buffing them. I'll need to look more into these particular items and figure out what's weird about the code.

**Comment by Siggyfreed** [comment]
Nevermind, I am just a ding dong and didn't have the mod loaded. Steel Legion boys are now balanced to the rest of the infantry in the modpack.
