### ISSUE TITLE
fix the thing so i can do the thing (blood pact)

### ISSUE THREAD

**Issue by LowGTechnoFight** [143rd-Siege-Army/143rdMod#77]
for the longest time we haven't used the tiow bloodpact units due to them being so tank because of the armor, do you think you can bring down the armor values so its strong but isnt as crazy as it used to be...

it would allow me to have the main op4 squadleader to be an "elite" boi

**Comment by Siggyfreed** [comment]
BP engineer armor values reduced for next patch, the other armors and base uniforms don't need tuning.
