### ISSUE TITLE
Either Heavy or Medium stubber ammo misnamed 

### ISSUE THREAD

**Issue by RoyalUnai** [143rd-Siege-Army/143rdMod#85]
One of the 143rd compact magazines for either heavy or medium stubber (I think heavy) two of the 150 round magazines are called amputators when one of them is supposed to be manstopper.

**Comment by Siggyfreed** [comment]
Fixed the typo in code, will test for next release.

**Comment by Siggyfreed** [comment]
Fixed in patch 1.3.1
