### ISSUE TITLE
Melee

### ISSUE THREAD

**Issue by missourivermont** [143rd-Siege-Army/143rdMod#87]
No idea if this can be changed or not (no biggie if can`t be). However zombies were melee tanks for me which makes me sad :(. Wondering if humans take more than 1-2 hits in general as well.

**Comment by Siggyfreed** [comment]
Zombie health and damage values are controlled via modules within the respective mod. This isn't something that we will need to address in the mod config directly. Contact your local Zeus for fixing zombies per mission!
