### ISSUE TITLE
Plasma

### ISSUE THREAD

**Issue by Helldog216** [143rd-Siege-Army/143rdMod#89]
Could we lower the weight of the safe plasma's rounds. The Krieg plasma gun's ammo is so heavy, for every one piece of ammunition, you can hold 5x that with the MK3 variant and that's not an exaggeration.

Just lowering the weight of the ammo to be the same would make it a little more convenient. As it stands, despite the risk, there is no way you're taking the Krieg plasma weapon over the MK3.

**Comment by Siggyfreed** [comment]
I can take a look at it for a balance pass

**Comment by Siggyfreed** [comment]
reducing flask weight from 27 to 15, should make the weapon more viable without making it a direct upgrade to the MK3
