### ISSUE TITLE
Melta Missile Fix

### ISSUE THREAD

**Issue by RoyalUnai** [143rd-Siege-Army/143rdMod#90]
Tested the melta missile against a cadian leman russ tank and it did no damage even when hitting a leman russ in the engine. I looked both as crew and zeus and damage was nada zip ziltch.

**Comment by Siggyfreed** [comment]
issue caused by a typo in the launcher submunition, it is now fixed and will detonate a leman in just a few rockets. give me more testing and lmk the details
