### ISSUE TITLE
New Krieg GL rounds balance

### ISSUE THREAD

**Issue by BenIde1** [143rd-Siege-Army/143rdMod#92]
After some testing it appears the new Krieg GL rounds weigh about a quarter of the weight of the original frag rounds. 

Perhaps the frag round weight should be halved and the new rounds weight doubled to bring them inline to each other? 

Also custom icons inline with the existing frag one would cool, nice to have not a necessity, just add a colored band on the shell icon to denote type using the Cadian GL round colors for continuity and easy identification.

**Comment by BenIde1** [comment]
Also the rounds could do with a little more OOMPH, even if it kind of feels like they already do. Right now there is still little reason to take the Krieg GL over the Cadian one due to fire rate when you are both firing the same rounds. 

Need some kind of incentive outside of aesthetics to take it so a bigger boom for the smaller mag size would work.

**Comment by Siggyfreed** [comment]
adjustments to damage values for gl rounds currently out of scope. weight has been adjusted, however, to make more rounds easier to carry. changing of round icons also currently out of scope cuz i dont feel like fucking with paa files to change them. new rounds inherit from ml700 rounds, however, and that problem might solve itself
