### ISSUE TITLE
fix the type 14

### ISSUE THREAD

**Issue by Tactical-Loli** [143rd-Siege-Army/143rdMod#94]
after some testing in its vanilla state during the consecrators joint op, its already balanced enough for the type of weapon it is. the ammo weight wont really be an issue since you wont need more than 2 mags. the firerate change you made however can stay, as it encourages ammo conservation

**Comment by Siggyfreed** [comment]
increasing the hit value and doubling the caliber value for the t14, bullets should no longer bounce off of targets and they should go down more reliably, gimme a test and lmk more deets

**Comment by Tactical-Loli** [comment]
Cool, lemme know when its updated
