### ISSUE TITLE
Increase size of invisible vox caster

### ISSUE THREAD

**Issue by RoyalUnai** [143rd-Siege-Army/143rdMod#99]
Main reason is opfor and other elements that require large amount gear and it kinda knee caps SL ability to do his role with his squad. For example opfor plants landmines or has to do X objective that zeus wants. Opfor LR can't really do that except stand around due to low carry compacity. Maybe buff it to same load size as the krieg AT or a lil above it?

**Comment by Siggyfreed** [comment]
fixed by rowooooo. carry weight increased to match carryall load.
